import "./globals.css";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import type { Metadata } from "next";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import Authprovider from "./api/auth/provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Authprovider>
          <Theme accentColor="iris" radius="large">
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </Authprovider>
      </body>
    </html>
  );
}
